import { Engagement } from "./types";

export const engagements: Engagement[] = [
  {
    id: 1,
    name: "Web",
    icon: "messenger",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 2,
    name: "Branding",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 3,
    name: "Operations",
    icon: "messenger",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 4,
    name: "Creative",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 5,
    name: "Functionality",
    icon: "messenger",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 6,
    name: "Research",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 7,
    name: "Creative",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 8,
    name: "Infrastructure",
    icon: "messenger",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 9,
    name: "Intranet",
    icon: "messenger",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 10,
    name: "Security",
    icon: "messenger",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 11,
    name: "Marketing",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 12,
    name: "Marketing",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 13,
    name: "Marketing",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 14,
    name: "Marketing",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
  {
    id: 15,
    name: "Marketing",
    icon: "instagram",
    engaged: 50,
    unique: 25,
    acquired: 66,
    conversion: 10,
    metaInfo: {},
  },
];
